config/routes.rb
Rails.application.routes.draw do
 

  devise_for :user_lojas
   resources :homes
  devise_for :users

  resources :lojas do
  	resources :reviews
  end 	
  # root 'lojas#index'

  root 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/loja.rb
class Loja < ApplicationRecord
	
	has_many :user_loja
	has_many :reviews


  has_attached_file :img_loja, styles: { lojas: "250x350>", lojas_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img_loja, content_type: /\Aimage\/.*\z/

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :loja
	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_loja.rb
class UserLoja < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_many :reviews
	has_many :lojas
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]


  def index
    @homes = Home.all
  end

  def show
  end

 
  def new
    @home = Home.new
  end

  def edit
  end

  private

    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController

before_action :achar_loja, only: [:show, :edit , :update, :destroy]
before_action :authenticate_user_loja!, only: [:new, :edit, :destroy] or before_action :authenticate_user!, only: [:index, :show]

def index
	@lojas = Loja.all.order("nome ASC")
end

def show 
	if @loja.reviews.blank?
		@average_review = 0
	else
		@average_review = @loja.reviews.average(:rating).round(2)
	end
end

def new
	@loja = Loja.new
end

def create
	@loja = Loja.new(loja_params)	

	if @loja.save
		redirect_to loja_path(@loja)	
	else
		render 'new'
	end
end

def edit
end

def update
	if @loja.update(loja_params)
		redirect_to loja_path(@loja)
	else
		render 'edit'
	end	

end

def destroy
	@loja.destroy
	redirect_to lojas_path
end

private

	def loja_params
		params.require(:loja).permit(:nome, :descricao,:email, :img_loja)
	end

	def achar_loja
		@loja = Loja.find(params[:id])
	end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :achar_loja
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	#before_action :authenticate_user_loja!, only: [:new, :edit, :destroy]
	

  	def new
		@review = Review.new
	end


	def create

		if user_signed_in?
		
		@review = Review.new(review_params)
		@review.loja_id = @loja.id
		@review.user_id = current_user.id

		end


		if user_loja_signed_in?

		@review = Review.new(review_params)
		@review.loja_id = @loja.id
		@review.user_loja_id = current_user_loja.id

		end

		if @review.save
			redirect_to loja_path(@loja)
		else	
			render 'new'	
		end

	end

	def edit
	end

	def update

		if @review.update(review_params)
			redirect_to loja_path(@loja)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to loja_path(@loja)
	end


	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def achar_loja
			@loja = Loja.find(params[:loja_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/homes/_form.html.erb
<%= simple_form_for @home, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                homes_path, :class => 'btn btn-default' %>
<% end %>

app/views/homes/edit.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/homes/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Landing Page - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/landing-page.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="/homes">Reclamo Mesmo</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">Sobre</a>
                    </li>
                    <li>
                        <a href="#services">Serviços</a>
                    </li>
                    <li>
                        <a href="#contact">Contatos</a>
                    </li>
 <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastre-se<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href= "/users/sign_up">Cadastrar Usuário</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/user_lojas/sign_in">Cadastrar Loja</a></li>
          </ul>
        </li>
    
       <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in?%>

                      <li><a href="/lojas">Lojas</a></li>
        <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>

        <% elsif user_loja_signed_in?%>

             <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Lojas<span class="caret"></span></a>
            <ul class="dropdown-menu">
             <li><a href="/lojas">Lojas</a></li>
                  <li role="separator" class="divider"></li>
              <li><a href="/lojas/new">Criar Loja</a></li>
            </ul>
          </li>
        <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>

      <% else %>
       
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/users/sign_in">Login para Usuários</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/user_lojas/sign_in">Login para Lojas</a></li>
            </ul>
          </li>
          <li><a href="/homes">Lojas</a></li>

      <% end %>
      </ul>

                


            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">

                    <div class="intro-message">
                        <h1>Reclamo Mesmo</h1>
                        <h3>Um site onde o consumidor é ouvido</h3>
                        <hr class="intro-divider">

                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="https://www.facebook.com/pages/Park-Shopping/157505207718351?fref=ts" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Facebook</span></a>
                            </li>
                            <li>
                                <a href="http://www.parkshopping.com.br/" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Park Shopping</span></a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/parkshoppingbsb/?hl=pt" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Instagram</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

    <a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Um site que preza <br>pela satisfação do cliente</h2>
                    <p class="lead">O Reclamo Mesmo<a href="/assets/imagem5.jpg/"> é um site que faz a ligação entre lojas físicas do Park Shopping e o cliente, onde este pode mostrar seu pensamento sobre um atendimento específico.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="images/965x500.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Suas insatisfações<br> e Elogios</h2>
                    <p class="lead"> serão levadas diretamente a loja responsável e esta irá te responder através desta plataforma. Você só precisa se cadastrar ao site e ter liberdade para reclamar!</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="/assets/images/imagem5.jpg/" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Nunca mais passe raiva!<br></h2>
                    <p class="lead">Utilizando o Reclamo Mesmo, você terá o feedback que merece.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="images/1632x1002.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Contatos</h2>
                </div>
                <div class="col-lg-6">
                    <h2>Não temos qualquer relação com o Park SHopping, somente fazemos a ponte entre consumidor e fornecedor. Logo, contate-se com eles!</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="http://www.parkshopping.com.br/" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Park Shopping</span></a>
                        </li>
                        <li>
                            <a href="http://www.procon.df.gov.br/" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Procon-DF</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/homes/new.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/homes/show.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              homes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_home_path(@home), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              home_path(@home),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EP3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <!-- Navigation -->
    <body>

     <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="/homes">Reclamo Mesmo</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">Sobre</a>
                    </li>
                    <li>
                        <a href="#services">Serviço</a>
                    </li>
                    <li>
                        <a href="#contact">Contato</a>
                    </li>
 <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastre-se<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href= "/users/sign_up">Cadastrar Usuário</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/user_lojas/sign_up">Cadastrar Loja</a></li>
          </ul>
        </li>
    
       <ul class="nav navbar-nav navbar-right">
<% if user_signed_in?%>

                      <li><a href="/lojas">Lojas</a></li>
        <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>

        <% elsif user_loja_signed_in?%>

             <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Lojas<span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><a href="/lojas">Lojas</a></li>
                  <li role="separator" class="divider"></li>
              <li><a href="/lojas/new">Criar Loja</a></li>
            </ul>
          </li>
        <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>

      <% else %>
       
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/users/sign_in">Login para Usuários</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/user_lojas/sign_in">Login para Lojas</a></li>
            </ul>
          </li>
           <li><a href="/homes">Lojas</a></li>
      <% end %>
      </ul>

                


            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <%= yield %>
  </body>
</html>

app/views/lojas/_form.html.erb
<%= simple_form_for @loja do |f|%>

  <%= f.file_field :img_loja %>
  <%= f.input :nome, label: "Nome da loja" %>
  <%= f.input :descricao%>
  <%= f.input :email %>
  <%= f.button :submit %>

<% end %>

app/views/lojas/edit.html.erb
<h1>Editar Loja</h1>


<%= render 'form' %>

app/views/lojas/index.html.erb
    <div class="row">

        <% @lojas.each do |loja| %>

            <div class="col-md-3">
                <a href="/lojas/<%= loja.id %>">
                    <%= image_tag loja.img_loja.url(:lojas), class: "loja" %>
                </a>
            </div>  

        <% end %>

</div>

app/views/lojas/new.html.erb
<h1> Nova Loja</h1>

<%= render 'form' %>

app/views/lojas/show.html.erb
<div class="row">

<div class="col-md-4">
<%= image_tag @loja.img_loja.url(:lojas_show), class: "loja-show" %>

</div>

	<div class="col-md-8">

<div class="loja-info">

			<h2 class="loja-title"><%= @loja.nome %></h2>
			<h2 class="avg-rating">Average Rating</h2>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span>Em um total de <%= @loja.reviews.count %> avaliações.</span>
			<p class="loja-desc"><%= @loja.descricao %></p>

	</div>


</div>

<div class="row">

	<div class="col-md-4">

		<div class="reviews">

			<!-- Where the reviews/ratings will go -->
			<h1>Reclamações</h1>
			<%= render @loja.reviews %>
 			
			<div>
				<%=link_to "Voltar", homes_path, class: "btn btn-primary" %>
			</div>
						<div>
				<<%= link_to "Reclamar",  new_loja_review_path(@loja) %>
			</div>
			<div>
				<%=link_to "Editar Loja", edit_loja_path, class: "btn btn-primary" %>
			</div>
						<div>
				<<%= link_to "Excluir",  loja_path(@loja), method: :delete, data: {confirm: "Tem certeza?"} %>
			</div>
		</div>	

	</div>

</div>


<script>
	$('.review-rating').raty({

		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		},
		path: '/assets/'

	});
</script>

<script>
	
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function(){
			return $(this).attr('data-score')
		}
	});

</script>

app/views/reviews/_form.html.erb
<%= simple_form_for([@loja, @loja.reviews.build]) do |f| %>

	<div id="rating-form">
		<label>Avaliação:<label>
	</div>

	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>

$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>

<% if user_signed_in? %>

	<% if review.user_id == current_user.id %>

<%= link_to  "Editar", edit_loja_review_path(review.loja, review) %>
<%= link_to  "Excluir", loja_review_path(review.loja, review), :method => :delete, data: { confirm: "Tem certeza?"}%>



	<% end %>

<% end %>

app/views/reviews/edit.html.erb
<h1>Editando Reclamação</h1>

<%= simple_form_for([@loja, @review]) do |f|%>

	<div id="rating-form">
		<label>Avaliação:<label>
	</div>
	
	<%= f.input :comment %>
	<%= f.button :submit %>	

<% end %>


<script>

$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
</script>

app/views/reviews/new.html.erb
<h1>Nova Reclamação</h1>

<%= render 'form' %>

app/views/user_lojas/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>